# Generated by Django 4.2.6 on 2023-10-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boop',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
